<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="5" passed="4" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-04-02T16:16:20 IST" name="PetSuite" finished-at="2024-04-02T16:16:26 IST" duration-ms="6015">
    <groups>
    </groups>
    <test started-at="2024-04-02T16:16:20 IST" name="PetTest" finished-at="2024-04-02T16:16:26 IST" duration-ms="6015">
      <class name="api.test.UserTests2">
        <test-method is-config="true" signature="setUp()[pri:0, instance:api.test.UserTests2@55a147cc]" started-at="2024-04-02T16:16:20 IST" name="setUp" finished-at="2024-04-02T16:16:21 IST" duration-ms="499" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="testFailedTest()[pri:0, instance:api.test.UserTests2@55a147cc]" started-at="2024-04-02T16:16:21 IST" name="testFailedTest" finished-at="2024-04-02T16:16:21 IST" duration-ms="11" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:976)
at org.testng.Assert.assertEquals(Assert.java:1010)
at api.test.UserTests2.testFailedTest(UserTests2.java:116)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testFailedTest -->
        <test-method signature="test_post_User()[pri:1, instance:api.test.UserTests2@55a147cc]" started-at="2024-04-02T16:16:21 IST" name="test_post_User" finished-at="2024-04-02T16:16:23 IST" duration-ms="2180" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test_post_User -->
        <test-method signature="getUserByName()[pri:2, instance:api.test.UserTests2@55a147cc]" started-at="2024-04-02T16:16:23 IST" name="getUserByName" finished-at="2024-04-02T16:16:24 IST" duration-ms="1027" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getUserByName -->
        <test-method signature="testUpdateUserByName()[pri:3, instance:api.test.UserTests2@55a147cc]" started-at="2024-04-02T16:16:24 IST" name="testUpdateUserByName" finished-at="2024-04-02T16:16:25 IST" duration-ms="1051" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testUpdateUserByName -->
        <test-method signature="testDeleteUserByUserName()[pri:4, instance:api.test.UserTests2@55a147cc]" started-at="2024-04-02T16:16:25 IST" name="testDeleteUserByUserName" finished-at="2024-04-02T16:16:26 IST" duration-ms="1029" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testDeleteUserByUserName -->
      </class> <!-- api.test.UserTests2 -->
    </test> <!-- PetTest -->
  </suite> <!-- PetSuite -->
</testng-results>
